name: 'UI Binance Testnet end-2-end test'
on:
  push:
    paths:
      - 'gateway-ui/**'

jobs:
  interaction-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./gateway-ui

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
            "yarn storybook --quiet --ci" \
            "npx wait-on tcp:6006 && yarn cypress:run"